=== SacredSkull/nightfall-incident-port/Assets/Entities/Software.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns="" id="NewDataSet" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="software">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="tool">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="attacks">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="basicattack">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="damage" type="xs:short" use="required" />
                        <xs:attribute name="self-minsize" type="xs:short" />
                        <xs:attribute default="1" name="range" type="xs:short" />
                        <xs:attribute name="self-health" type="xs:short" />
                        <xs:attribute name="self-result" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="attributemodifier">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="1" maxOccurs="unbounded" name="attribute">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required" />
                              <xs:attribute name="value" type="xs:short" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="type" type="xs:string" use="required" />
                        <xs:attribute name="description" type="xs:string" />
                        <xs:attribute name="range" type="xs:string" default="1" />
                        <xs:attribute name="self-minsize" type="xs:short" />
                        <xs:attribute name="self-health" type="xs:short" />
                        <xs:attribute name="self-result" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="mapmodifier">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="value" type="xs:short" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="description" type="xs:string" />
            <xs:attribute name="string_id" type="xs:string" use="required" />
            <xs:attribute default="1" name="movement" type="xs:short" />
            <xs:attribute default="1" name="maxsize" type="xs:short" />
            <xs:attribute default="100" name="cost" type="xs:short" />
            <xs:attribute default="1" name="level" type="xs:short" />
            <xs:attribute name="governor" type="xs:string" />
            <xs:attribute default="false" name="isEnemy" type="xs:boolean" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element msdata:IsDataSet="true" msdata:UseCurrentLocale="true" name="NewDataSet">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="software" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SacredSkull/nightfall-incident-port/Assets/Entities/Sentries.xml
<?xml version="1.0" encoding="utf-8" ?>
<software version="1.0" xsi:noNamespaceSchemaLocation="Software.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- Sentinel programs -->

    <tool name="Sentinel" description="Corporate data minion" string_id="sentinel_1" movement="1" maxsize="3" level="1">
        <attacks>
            <basicattack name="Swing" damage="2"/>
        </attacks>
    </tool>
    <tool name="Sentinel v2" description="Corporate data soldier" string_id="sentinel_2"  movement="2" maxsize="4" level="2">
        <attacks>
            <basicattack name="Cut" damage="2"/>
        </attacks>
    </tool>
    <tool name="Sentinel v3" description="ACCESS IS DENIED" string_id="sentinel_3"  movement="2" maxsize="4" level="3">
        <attacks>
            <basicattack name="Taser" damage="4"/>
        </attacks>
    </tool>


    <!-- Ranged watchman programs -->

    <tool name="Watchman" description="Corporate first-contact enforcer" string_id="watchman_1" movement="1" maxsize="2" level="1">
        <attacks>
            <basicattack name="poke" range="3" damage="1"/>
        </attacks>
    </tool>
    <tool name="Watchman X" description="Faster, stronger first-contact striker" string_id="watchman_2"  movement="2" maxsize="4" level="2">
        <attacks>
            <basicattack name="Probe" range="3" damage="2"/>
        </attacks>
    </tool>
    <tool name="Watchman SP" description="Qui Custodiet Ipsos Custodes?" string_id="watchman_3"  movement="2" maxsize="4" level="3">
        <attacks>
            <basicattack name="Snipe" range="3" damage="3"/>
        </attacks>
    </tool>


    <!--  Dog programs -->

    <tool name="Guard Pup" description="No bark, very little bite" string_id="dog_1" movement="3" maxsize="2" level="1">
        <attacks>
            <basicattack name="Nibble" damage="2"/>
        </attacks>
    </tool>
    <tool name="Guard Dog" description="Thorough-bred for eliminating intruders" string_id="dog_2"  movement="3" maxsize="3" level="2">
        <attacks>
            <basicattack name="Byte" damage="2"/>
        </attacks>
    </tool>
    <tool name="Attack Dog" description="It'll be over, quickly" string_id="dog_3"  movement="4" maxsize="7" level="3">
        <attacks>
            <basicattack name="Megabyte" damage="3"/>
        </attacks>
    </tool>


    <!-- Warden programs -->

    <tool name="Warden" description="Slow and steady corporate thug" string_id="warden_1" movement="1" maxsize="5" level="1">
        <attacks>
            <basicattack name="Thump" damage="3"/>
        </attacks>
    </tool>
    <tool name="Warden++" description="'Sir, you shouldn't be in here.'" string_id="warden_2"  movement="2" maxsize="6" level="2">
        <attacks>
            <basicattack name="Bash" damage="5"/>
        </attacks>
    </tool>
    <tool name="Warden_ALPHA" description="Puts the 'force' in enforcement"  string_id="warden_3"  movement="3" maxsize="7" level="3">
        <attacks>
            <basicattack name="Crash" damage="7"/>
        </attacks>
    </tool>


    <!-- Ranged static sensor programs -->

    <tool  name="Sensor" description="Long range program eradicator" string_id="sensor_1"  movement="0" maxsize="1" level="2">
        <attacks>
            <basicattack name="Ping" range="5" damage="1"/>
        </attacks>
    </tool>
    <tool name="Sonar" description="Longer range program eradicator" string_id="sensor_2"  movement="0" maxsize="1" level="3">
        <attacks>
        	<basicattack name="Scan" range="8" damage="1"/>
        </attacks>
    </tool>
    <tool name="Radar" description="You're probably in range" string_id="radar_1"  movement="0" maxsize="1" level="4">
        <attacks>
        	<basicattack name="Phase" range="5" damage="2"/>
        </attacks>
    </tool>


    <!-- One offs/boss programs -->

    <tool name="Firewall" description="Defends corporate memory space" string_id="firewall_1"  movement="2" maxsize="20" level="3">
        <attacks>
            <basicattack name="Burn" damage="1"/>
        </attacks>
    </tool>

    <tool name="Sumo" description="A massive, slow moving powerhouse" string_id="esumo_1" movement="12" maxsize="2" level="4">
        <attacks>
            <basicattack name="Dataslam"  damage="6" self-minsize="6" />
        </attacks>
    </tool>

    <tool name="MandelBug" description="Details not disclosed" string_id="bug_2" movement="5" maxsize="1" level="4">
        <attacks>
        	<basicattack name="Exploit"  damage="4"/>
        </attacks>
    </tool>

    <tool name="Boss" description="root@localhost:~#" string_id="boss_1" movement="6" maxsize="25" level="5">
        <attacks>
        	<basicattack name="kill -SIGKILL" range="5" damage="5"/>
        </attacks>
    </tool>
</software>
